---
title: Fluxus Frequency
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://fluxusfrequency.github.io
subtitle: How I Hacked The Mainframe
author: Ben Lewis
simple_search: https://www.google.com/search
description: 
date_format: ordinal
subscribe_rss: "/atom.xml"
subscribe_email: 
email: 
root: "/"
permalink: "/blog/:year/:month/:day/:title/"
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
  - autolink
  - footnotes
  - smart
highlighter: pygments
paginate: 10
paginate_path: posts/:num
recent_posts: 5
excerpt_link: Read on &rarr;
excerpt_separator: "<!--more-->"
titlecase: true
default_asides:
- asides/recent_posts.html
- asides/github.html
- asides/delicious.html
- asides/pinboard.html
- asides/googleplus.html
github_user: 
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true
twitter_user: fluxusfrequency
twitter_tweet_button: true
google_plus_one: false
google_plus_one_size: medium
googleplus_user: 
googleplus_hidden: false
pinboard_user: 
pinboard_count: 3
delicious_user: 
delicious_count: 3
disqus_short_name: 
disqus_show_comment_count: false
google_analytics_tracking_id: 
facebook_like: false
